const fs = require("fs");
const code = [
"\"use client\"","",
"import { useState, useEffect } from \"react\"","import { motion, AnimatePresence } from \"framer-motion\"","import { ShoppingCart, X, MapPin } from \"lucide-react\"","",
"const BUYERS = [",
"  { name: \"Ricardo M.\", city: \"Andir\u00e1, PR\" },",
"  { name: \"Ana Paula S.\", city: \"Londrina, PR\" },",
"  { name: \"Carlos E.\", city: \"Ourinhos, SP\" },",
"  { name: \"Fernanda L.\", city: \"Aparecida, SP\" },",
"  { name: \"Roberto J.\", city: \"Cambar\u00e1, PR\" },",
"  { name: \"Mariana C.\", city: \"Cascavel, PR\" },",
"  { name: \"Paulo H.\", city: \"Maring\u00e1, PR\" },",
"  { name: \"Juliana F.\", city: \"Jacarezinho, PR\" },",
"  { name: \"Marcos V.\", city: \"Assis, SP\" },",
"  { name: \"Beatriz R.\", city: \"Corn\u00e9lio Proc\u00f3pio, PR\" },",
"  { name: \"Eduardo S.\", city: \"Santo Ant\u00f4nio da Platina, PR\" },",
"  { name: \"Camila T.\", city: \"Ibaiti, PR\" },",
"  { name: \"Lucas A.\", city: \"Bandeirantes, PR\" },",
"  { name: \"Patr\u00edcia M.\", city: \"Ribeir\u00e3o Preto, SP\" },",
"  { name: \"Diego N.\", city: \"Aracaju, SE\" },",
"  { name: \"Sandra O.\", city: \"Salvador, BA\" },",
"  { name: \"Thiago P.\", city: \"Bras\u00edlia, DF\" },",
"  { name: \"Renata G.\", city: \"Belo Horizonte, MG\" },",
"]","",
"const TIMES = [\"H\u00e1 1 minuto\", \"H\u00e1 2 minutos\", \"H\u00e1 3 minutos\", \"H\u00e1 4 minutos\", \"H\u00e1 5 minutos\"]","",
"export default function AdvancedNotifications() {",
"  const [visible, setVisible] = useState(false)",
"  const [buyer, setBuyer] = useState(BUYERS[0])",
"  const [time, setTime] = useState(TIMES[0])","",
"  useEffect(() => {",
"    let mounted = true",
"    const trigger = () => {",
"      // RANDOM: 25s a 50s",
"      const delay = Math.floor(Math.random() * 25000) + 25000",
"      setTimeout(() => {",
"        if (!mounted) return",
"        setBuyer(BUYERS[Math.floor(Math.random() * BUYERS.length)])",
"        setTime(TIMES[Math.floor(Math.random() * TIMES.length)])",
"        setVisible(true)",
"        // Esconde apos 6s",
"        setTimeout(() => {",
"          if (!mounted) return",
"          setVisible(false)",
"          trigger()",
"        }, 6000)",
"      }, delay)",
"    }",
"    trigger()",
"    return () => { mounted = false }",
"  }, [])","",
"  return (",
"    <AnimatePresence>",
"      {visible && (",
"        <motion.div",
"          initial={{ x: -100, opacity: 0 }}",
"          animate={{ x: 0, opacity: 1 }}",
"          exit={{ x: -100, opacity: 0 }}",
"          className=\"fixed bottom-4 left-4 z-40 bg-white rounded-xl shadow-2xl border border-gray-200 p-4 max-w-xs\"",
"        >",
"          <button onClick={() => setVisible(false)} className=\"absolute top-2 right-2 text-gray-300 hover:text-gray-500\">",
"            <X className=\"w-4 h-4\" />",
"          </button>",
"          <div className=\"flex items-center gap-3\">",
"            <div className=\"w-10 h-10 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0\">",
"              <ShoppingCart className=\"w-5 h-5 text-green-600\" />",
"            </div>",
"            <div>",
"              <p className=\"text-sm font-bold text-gray-900\">Compra Confirmada!</p>",
"              <p className=\"text-xs text-gray-600\">Algu\u00e9m de <strong className=\"text-green-600\">{buyer.city}</strong> acabou de garantir o Pethere GPS</p>",
"              <p className=\"text-xs text-gray-400 flex items-center gap-1 mt-1\"><MapPin className=\"w-3 h-3\" />{time}</p>",
"            </div>",
"          </div>",
"        </motion.div>",
"      )}",
"    </AnimatePresence>",
"  )","}",
].join("\n");
fs.writeFileSync("components/AdvancedNotifications.tsx", code, "utf8");
console.log("[OK] Notificacoes reescritas: 25-50s random, 18 cidades reais, cleanup on unmount");
