const fs = require("fs");

// === 1. Rewrite lib/pagarme.ts for V5 REST API ===
const pagarme = [
"const PAGARME_SECRET = process.env.PAGARME_SECRET_KEY || \"\"","const PAGARME_URL = \"https://api.pagar.me/core/v5\"","",
"function getAuth() { return \"Basic \" + Buffer.from(PAGARME_SECRET + \":\").toString(\"base64\") }","",
"export async function createPixOrder(data: { name: string; email: string; phone: string; document: string; amount: number; orderId: string }) {",
"  const body = {",
"    items: [{ amount: data.amount, description: \"Pethere GPS + Plano 24 meses\", quantity: 1, code: \"GPS-G2\" }],",
"    customer: {",
"      name: data.name, email: data.email, type: \"individual\",",
"      document: data.document.replace(/\\D/g, \"\"),",
"      phones: { mobile_phone: { country_code: \"55\", area_code: data.phone.replace(/\\D/g, \"\").slice(0,2), number: data.phone.replace(/\\D/g, \"\").slice(2) } }",
"    },",
"    payments: [{ payment_method: \"pix\", pix: { expires_in: 900 } }],",
"    metadata: { order_id: data.orderId }",
"  }",
"  const res = await fetch(PAGARME_URL + \"/orders\", {",
"    method: \"POST\",",
"    headers: { \"Content-Type\": \"application/json\", \"Authorization\": getAuth() },",
"    body: JSON.stringify(body)",
"  })",
"  const result = await res.json()",
"  if (!res.ok) return { success: false, error: result.message || \"Erro Pagar.me\" }",
"  const charge = result.charges?.[0]",
"  const pix = charge?.last_transaction",
"  return {",
"    success: true, orderId: result.id, status: result.status,",
"    pixQrCode: pix?.qr_code, pixQrCodeUrl: pix?.qr_code_url,",
"    pixExpiresAt: pix?.expires_at",
"  }",
"}","",
"export async function createCardOrder(data: { name: string; email: string; phone: string; document: string; amount: number; installments: number; orderId: string; cardToken?: string }) {",
"  const body = {",
"    items: [{ amount: data.amount, description: \"Pethere GPS + Plano 24 meses\", quantity: 1, code: \"GPS-G2\" }],",
"    customer: {",
"      name: data.name, email: data.email, type: \"individual\",",
"      document: data.document.replace(/\\D/g, \"\"),",
"      phones: { mobile_phone: { country_code: \"55\", area_code: data.phone.replace(/\\D/g, \"\").slice(0,2), number: data.phone.replace(/\\D/g, \"\").slice(2) } }",
"    },",
"    payments: [{ payment_method: \"credit_card\", credit_card: { installments: data.installments, statement_descriptor: \"PETHERE GPS\", card_token: data.cardToken || \"\" } }],",
"    metadata: { order_id: data.orderId }",
"  }",
"  const res = await fetch(PAGARME_URL + \"/orders\", {",
"    method: \"POST\",",
"    headers: { \"Content-Type\": \"application/json\", \"Authorization\": getAuth() },",
"    body: JSON.stringify(body)",
"  })",
"  const result = await res.json()",
"  if (!res.ok) return { success: false, error: result.message || \"Erro Pagar.me\" }",
"  return { success: true, orderId: result.id, status: result.status }",
"}","",
"export async function getOrder(orderId: string) {",
"  const res = await fetch(PAGARME_URL + \"/orders/\" + orderId, {",
"    headers: { \"Authorization\": getAuth() }",
"  })",
"  if (!res.ok) return null",
"  return res.json()",
"}"
].join("\n");
fs.writeFileSync("lib/pagarme.ts", pagarme, "utf8");
console.log("[OK] lib/pagarme.ts reescrito para V5 REST API");

// === 2. Rewrite checkout/create API ===
const checkout = [
"import { NextRequest, NextResponse } from \"next/server\"","import { prisma } from \"@/lib/prisma\"","import { createPixOrder, createCardOrder } from \"@/lib/pagarme\"","",
"function generateOrderNumber() { return \"PET-\" + Date.now().toString(36).toUpperCase() + Math.random().toString(36).slice(2,5).toUpperCase() }","",
"export async function POST(request: NextRequest) {",
"  try {",
"    const body = await request.json()",
"    const { name, document, whatsapp, email, cep, address, number, complement, neighborhood, city, state, quantity, payment_method, order_bump, total, customer_type, responsible_name } = body","",
"    if (!name || !document || !email) return NextResponse.json({ error: \"Dados obrigat\u00f3rios\" }, { status: 400 })","",
"    const orderNumber = generateOrderNumber()",
"    const shippingAddr = [address, number, complement, neighborhood, city, state, cep].filter(Boolean).join(\", \")","",
"    // Criar pedido no banco",
"    const order = await prisma.order.create({",
"      data: {",
"        orderNumber,",
"        customerName: name,",
"        customerEmail: email,",
"        customerPhone: whatsapp || \"\",",
"        customerCPF: document,",
"        customerState: state || null,",
"        shippingAddress: shippingAddr,",
"        subtotal: total,",
"        shipping: 0,",
"        total: total,",
"        paymentMethod: payment_method,",
"        paymentStatus: \"pending\",",
"        status: \"pending\",",
"      }",
"    })","",
"    // Processar pagamento no Pagar.me",
"    const amountCents = Math.round(total * 100)",
"    let paymentResult","",
"    if (payment_method === \"pix\") {",
"      paymentResult = await createPixOrder({ name, email, phone: whatsapp, document, amount: amountCents, orderId: order.id })",
"    } else {",
"      paymentResult = await createCardOrder({ name, email, phone: whatsapp, document, amount: amountCents, installments: 12, orderId: order.id })",
"    }","",
"    if (paymentResult.success) {",
"      await prisma.order.update({ where: { id: order.id }, data: { paymentId: paymentResult.orderId, paymentStatus: \"waiting_payment\", status: \"waiting_payment\" } })",
"    } else {",
"      await prisma.order.update({ where: { id: order.id }, data: { paymentStatus: \"failed\", status: \"failed\" } })",
"      return NextResponse.json({ error: paymentResult.error || \"Erro no pagamento\" }, { status: 400 })",
"    }","",
"    return NextResponse.json({",
"      success: true,",
"      orderNumber: order.orderNumber,",
"      id: order.id,",
"      total: order.total,",
"      pixQrCode: paymentResult.pixQrCode || null,",
"      pixQrCodeUrl: paymentResult.pixQrCodeUrl || null,",
"    })",
"  } catch (error: any) {",
"    console.error(\"Checkout error:\", error)",
"    return NextResponse.json({ error: error.message || \"Erro interno\" }, { status: 500 })",
"  }","}"
].join("\n");
fs.writeFileSync("app/api/checkout/create/route.ts", checkout, "utf8");
console.log("[OK] checkout/create reescrito para schema real + Pagar.me V5");

console.log("\n=== PAGAR.ME V5 INTEGRADO ===");
console.log("Adicione no .env.local:");
console.log("  PAGARME_SECRET_KEY=sk_test_SUA_CHAVE_AQUI");
