const fs = require("fs");
const code = [
"\"use client\"","",
"import { useState, useEffect, useRef } from \"react\"","import { motion, AnimatePresence } from \"framer-motion\"","import { X, Send, Loader2, Sparkles, MessageCircle } from \"lucide-react\"","",
"interface Message {","  role: \"user\" | \"assistant\"","  content: string","  timestamp: Date","}","",
"export default function SalesAI() {",
"  const [isOpen, setIsOpen] = useState(false)",
"  const [messages, setMessages] = useState<Message[]>([])",
"  const [input, setInput] = useState(\"\")",
"  const [isLoading, setIsLoading] = useState(false)",
"  const [hasTriggeredExit, setHasTriggeredExit] = useState(false)",
"  const [exitIntentMode, setExitIntentMode] = useState(false)",
"  const messagesEndRef = useRef<HTMLDivElement>(null)",
"  const pageLoadTime = useRef(Date.now())","",
"  // EXIT INTENT - STRICT: s\u00f3 topo, s\u00f3 1x, s\u00f3 ap\u00f3s 10s na p\u00e1gina",
"  useEffect(() => {",
"    const handleMouseLeave = (e: MouseEvent) => {",
"      const timeOnPage = Date.now() - pageLoadTime.current",
"      if (",
"        e.clientY <= 0 &&",
"        e.clientX > 0 &&",
"        e.clientX < window.innerWidth &&",
"        !hasTriggeredExit &&",
"        !isOpen &&",
"        timeOnPage > 10000",
"      ) {",
"        setExitIntentMode(true)",
"        setIsOpen(true)",
"        setHasTriggeredExit(true)",
"        setTimeout(() => {",
"          setMessages([{",
"            role: \"assistant\",",
"            content: \"\u26a0\ufe0f Espera! Vi que voc\u00ea est\u00e1 saindo...\\n\\n\ud83c\udf81 Posso liberar o FRETE GR\u00c1TIS para voc\u00ea agora!\\n\\nAl\u00e9m disso, tenho um cupom de 10% exclusivo.\\n\\n\ud83d\udcb0 Quer garantir?\",",
"            timestamp: new Date()",
"          }])",
"        }, 500)",
"      }",
"    }",
"    document.addEventListener(\"mouseleave\", handleMouseLeave)",
"    return () => document.removeEventListener(\"mouseleave\", handleMouseLeave)",
"  }, [hasTriggeredExit, isOpen])","",
"  // Mensagem inicial - S\u00d3 no clique manual (n\u00e3o no exit intent)",
"  useEffect(() => {",
"    if (isOpen && messages.length === 0 && !exitIntentMode) {",
"      setMessages([{",
"        role: \"assistant\",",
"        content: \"\ud83d\udc4b Ol\u00e1! Sou a Ana, Especialista da Pethere.\\n\\nQual sua d\u00favida sobre o rastreador GPS?\\n\\nEstou aqui para ajudar! \ud83d\udc15\",",
"        timestamp: new Date()",
"      }])",
"    }",
"  }, [isOpen, exitIntentMode])","",
"  useEffect(() => {",
"    messagesEndRef.current?.scrollIntoView({ behavior: \"smooth\" })",
"  }, [messages])","",
"  const sendMessage = async () => {",
"    if (!input.trim() || isLoading) return",
"    const userMessage: Message = { role: \"user\", content: input, timestamp: new Date() }",
"    setMessages(prev => [...prev, userMessage])",
"    setInput(\"\")",
"    setIsLoading(true)",
"    try {",
"      const response = await fetch(\"/api/chat\", {",
"        method: \"POST\",",
"        headers: { \"Content-Type\": \"application/json\" },",
"        body: JSON.stringify({ message: input, history: messages.map(m => ({ role: m.role, content: m.content })) })",
"      })",
"      const data = await response.json()",
"      if (data.success) {",
"        setMessages(prev => [...prev, { role: \"assistant\", content: data.reply, timestamp: new Date() }])",
"      } else { throw new Error(data.error) }",
"    } catch {",
"      setMessages(prev => [...prev, { role: \"assistant\", content: \"\ud83d\ude05 Desculpe! Dificuldades t\u00e9cnicas.\\n\\n\u2705 Finalize em: www.oseupetaqui.com.br\\n\\n\ud83d\udcb0 12x R$ 39,90\", timestamp: new Date() }])",
"    } finally { setIsLoading(false) }",
"  }","",
"  return (",
"    <div className=\"fixed bottom-6 right-6 z-50 flex flex-col items-end\">",
"      <AnimatePresence>",
"        {isOpen && (",
"          <motion.div initial={{ opacity: 0, y: 100 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 100 }} className=\"mb-4 w-96 max-w-[calc(100vw-3rem)] bg-white rounded-2xl shadow-2xl border-2 border-slate-200 overflow-hidden\">",
"            {/* HEADER */}",
"            <div className=\"bg-slate-900 p-4 flex items-center justify-between\">",
"              <div className=\"flex items-center gap-3\">",
"                <div className=\"relative\">",
"                  <div className=\"w-12 h-12 rounded-full border-3 border-green-500 overflow-hidden bg-slate-700\">",
"                    <img src=\"/ana-especialista.avif\" alt=\"Ana\" className=\"w-full h-full object-cover\" />",
"                  </div>",
"                  <span className=\"absolute bottom-0 right-0 w-3.5 h-3.5 bg-green-500 rounded-full border-2 border-white animate-pulse\"></span>",
"                </div>",
"                <div>",
"                  <p className=\"text-white font-black text-sm\">Ana Paula Silva</p>",
"                  <p className=\"text-green-400 text-xs font-medium\">\u25cf Online agora</p>",
"                  <p className=\"text-slate-400 text-xs\">Especialista Pethere FRT</p>",
"                </div>",
"              </div>",
"              <button onClick={() => setIsOpen(false)} className=\"text-slate-400 hover:text-white p-1\"><X className=\"w-5 h-5\" /></button>",
"            </div>","",
"            {/* MENSAGENS */}",
"            <div className=\"h-96 bg-slate-50 p-4 overflow-y-auto\">",
"              {exitIntentMode && messages.length === 1 && (",
"                <div className=\"bg-red-50 border-2 border-red-500 rounded-xl p-3 mb-4 animate-pulse\">",
"                  <p className=\"text-red-800 font-bold text-center text-sm\">\ud83d\udea8 OFERTA EXCLUSIVA \ud83d\udea8</p>",
"                </div>",
"              )}",
"              {messages.map((message, index) => (",
"                <motion.div key={index} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className={`flex ${message.role === \"user\" ? \"justify-end\" : \"justify-start\"} mb-4`}>",
"                  <div className={`max-w-[80%] rounded-2xl px-4 py-3 ${message.role === \"user\" ? \"bg-green-600 text-white rounded-br-none\" : \"bg-white text-slate-900 rounded-bl-none shadow-md border border-slate-200\"}`}>",
"                    {message.role === \"assistant\" && (",
"                      <div className=\"flex items-center gap-2 mb-2\">",
"                        <div className=\"w-6 h-6 rounded-full overflow-hidden border border-green-500\"><img src=\"/ana-especialista.avif\" alt=\"Ana\" className=\"w-full h-full object-cover\" /></div>",
"                        <span className=\"text-xs font-bold text-green-600\">Ana</span>",
"                        <Sparkles className=\"w-3 h-3 text-yellow-500\" />",
"                      </div>",
"                    )}",
"                    <p className=\"text-sm leading-relaxed whitespace-pre-wrap\">{message.content}</p>",
"                    <p className={`text-xs mt-2 ${message.role === \"user\" ? \"text-green-200\" : \"text-slate-400\"}`}>{message.timestamp.toLocaleTimeString(\"pt-BR\", { hour: \"2-digit\", minute: \"2-digit\" })}</p>",
"                  </div>",
"                </motion.div>",
"              ))}","",
"              {isLoading && (",
"                <div className=\"flex justify-start mb-4\">",
"                  <div className=\"bg-white rounded-2xl px-4 py-3 shadow-md border flex items-center gap-2\">",
"                    <div className=\"w-6 h-6 rounded-full overflow-hidden border border-green-500\"><img src=\"/ana-especialista.avif\" alt=\"Ana\" className=\"w-full h-full object-cover\" /></div>",
"                    <Loader2 className=\"w-5 h-5 text-green-500 animate-spin\" />",
"                    <span className=\"text-sm text-slate-600\">Ana digitando...</span>",
"                  </div>",
"                </div>",
"              )}",
"              <div ref={messagesEndRef} />",
"            </div>","",
"            {/* RESPOSTAS R\u00c1PIDAS */}",
"            {messages.length === 1 && !isLoading && (",
"              <div className=\"px-4 py-3 bg-white border-t\">",
"                <p className=\"text-xs text-slate-500 mb-2\">\u26a1 Perguntas r\u00e1pidas:</p>",
"                <div className=\"flex flex-wrap gap-2\">",
"                  {[",
"                    exitIntentMode ? \"Quero frete gr\u00e1tis!\" : \"Como funciona?\",",
"                    exitIntentMode ? \"E o cupom?\" : \"Qual o pre\u00e7o?\",",
"                    exitIntentMode ? \"Fechar agora!\" : \"Funciona bem?\"",
"                  ].map((quick, i) => (",
"                    <button key={i} onClick={() => { setInput(quick); setTimeout(() => sendMessage(), 100) }} className=\"text-xs bg-slate-100 hover:bg-green-500 hover:text-white text-slate-700 px-3 py-2 rounded-full border transition-all\">{quick}</button>",
"                  ))}",
"                </div>",
"              </div>",
"            )}","",
"            {/* INPUT */}",
"            <div className=\"p-4 bg-white border-t\">",
"              <div className=\"flex gap-2\">",
"                <input type=\"text\" value={input} onChange={(e) => setInput(e.target.value)} onKeyPress={(e) => e.key === \"Enter\" && sendMessage()} placeholder=\"Digite sua mensagem...\" className=\"flex-1 px-4 py-3 bg-slate-50 border-2 border-slate-200 rounded-xl focus:border-green-500 focus:outline-none text-sm\" disabled={isLoading} />",
"                <button onClick={sendMessage} disabled={!input.trim() || isLoading} className=\"bg-green-500 hover:bg-green-600 disabled:opacity-50 text-white p-3 rounded-xl\"><Send className=\"w-5 h-5\" /></button>",
"              </div>",
"            </div>",
"          </motion.div>",
"        )}",
"      </AnimatePresence>","",
"      {/* BOT\u00c3O FLUTUANTE */}",
"      {!isOpen && (",
"        <motion.button initial={{ scale: 0 }} animate={{ scale: 1 }} whileHover={{ scale: 1.05 }} onClick={() => { setExitIntentMode(false); setIsOpen(true) }} className=\"group flex items-center gap-3 bg-green-600 hover:bg-green-500 text-white pl-4 pr-6 py-3 rounded-full shadow-2xl\">",
"          <div className=\"relative\">",
"            <div className=\"w-12 h-12 rounded-full border-2 border-white overflow-hidden bg-slate-700\">",
"              <img src=\"/ana-especialista.avif\" alt=\"Suporte\" className=\"w-full h-full object-cover\" />",
"            </div>",
"          </div>",
"          <div className=\"text-left\">",
"            <p className=\"text-xs text-green-100 font-medium\">Tenho D\u00favidas?</p>",
"            <p className=\"text-sm font-black\">Falar com Especialista</p>",
"          </div>",
"          <MessageCircle className=\"w-5 h-5 group-hover:scale-110 transition-transform\" />",
"        </motion.button>",
"      )}",
"    </div>",
"  )","}",
].join("\n");
fs.writeFileSync("components/SalesAI.tsx", code, "utf8");
console.log("[OK] SalesAI.tsx corrigido!");
console.log("Mudancas:");
console.log("  - Removido: notificacao vermelha no botao (nao abre sozinho)");
console.log("  - Exit intent: so dispara apos 10s na pagina");
console.log("  - Exit intent: verifica clientX dentro da viewport");
console.log("  - Manual: so abre no clique do botao");
