const fs = require("fs");
let c = fs.readFileSync("app/page.tsx", "utf8");
const START = "{/* HERO DARK";
const END = "</section>\n\n        {/* TABELA";
const s = c.indexOf(START);
const e = c.indexOf(END);
if (s===-1||e===-1){console.log("Marcadores nao encontrados. s="+s+" e="+e);process.exit(1)}
console.log("Hero encontrado: linhas "+c.substring(0,s).split("\n").length+" a "+c.substring(0,e).split("\n").length);

// Add Coffee import if missing
if (!c.includes("Coffee")) {
  c = c.replace("import {", "import {\n  Coffee,");
  console.log("Coffee import adicionado");
}

const H = [];
H.push("{/* HERO DARK - CAF\u00c9 VS SEGURAN\u00c7A */}");
H.push("        <section className=\"bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 py-12 sm:py-16\">");
H.push("          <div className=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">");
H.push("            <div className=\"grid lg:grid-cols-2 gap-8 items-center\">");
H.push("");
H.push("              <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className=\"space-y-6\">");
H.push("");
H.push("                {/* Badge Estoque */}");
H.push("                <div className=\"inline-flex items-center gap-2 bg-red-500/20 border border-red-500/50 text-red-400 px-4 py-2 rounded-full shadow-md text-xs font-bold animate-pulse\">");
H.push("                  <Gift className=\"w-4 h-4\" />");
H.push("                  Estoque Promocional acabando em... 111 unidades!");
H.push("                </div>");
H.push("");
H.push("                {/* Headline */}");
H.push("                <h1 className=\"text-3xl sm:text-4xl lg:text-5xl font-black text-white leading-tight\">");
H.push("                  Um cafezinho custa R$ 6,00.<br />");
H.push("                  A vida do seu pet custa <span className=\"text-green-400\">R$ 0,65</span>.");
H.push("                </h1>");
H.push("");
H.push("                <p className=\"text-base sm:text-lg text-slate-300 leading-relaxed\">");
H.push("                  Voc\u00ea vai arriscar perder seu melhor amigo por moedas? Garanta a tecnologia FRT pelo menor pre\u00e7o da hist\u00f3ria.");
H.push("                </p>");
H.push("");
H.push("                {/* Badge R$ 0,65/dia */}");
H.push("                <div className=\"bg-blue-500/10 border border-blue-500/30 rounded-xl p-4 flex items-center gap-4\">");
H.push("                  <div className=\"text-4xl sm:text-5xl font-black text-blue-400\">");
H.push("                    R$ 0,65<span className=\"text-lg text-blue-400/60\">/dia</span>");
H.push("                  </div>");
H.push("                  <div className=\"text-sm text-slate-300\">");
H.push("                    Menos que uma bala na padaria.<br />");
H.push("                    <span className=\"font-bold text-white\">12x de R$ 39,90 no cart\u00e3o.</span>");
H.push("                  </div>");
H.push("                </div>");
H.push("");
H.push("                {/* CTA */}");
H.push("                <div className=\"flex flex-col sm:flex-row gap-3\">");
H.push("                  <button onClick={handleBuyClick} className=\"bg-green-500 hover:bg-green-600 text-white font-bold px-8 py-4 rounded-lg text-lg shadow-lg shadow-green-500/30 transition-all flex items-center justify-center gap-2 group\">");
H.push("                    <ShoppingCart className=\"w-5 h-5\" />");
H.push("                    <span>QUERO MEU GPS GR\u00c1TIS AGORA</span>");
H.push("                    <ChevronRight className=\"w-5 h-5 group-hover:translate-x-1 transition-transform\" />");
H.push("                  </button>");
H.push("                </div>");
H.push("              </motion.div>");
H.push("");
H.push("              {/* RIGHT: Video + Compara\u00e7\u00e3o */}");
H.push("              <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className=\"space-y-4\">");
H.push("                <div className=\"relative\">");
H.push("                  <div className=\"absolute -inset-3 bg-gradient-to-r from-green-500/20 to-emerald-500/20 rounded-2xl blur-xl\"></div>");
H.push("                  <div className=\"relative bg-slate-800 rounded-xl p-3 shadow-2xl border border-slate-700\">");
H.push("                    <div className=\"aspect-video rounded-lg overflow-hidden\">");
H.push("                      <YouTubePlayer videoId=\"EcN6NLiqSXk\" autoplay={true} loop={true} controls={true} />");
H.push("                    </div>");
H.push("                  </div>");
H.push("                </div>");
H.push("");
H.push("                {/* Compara\u00e7\u00e3o Caf\u00e9 vs Prote\u00e7\u00e3o */}");
H.push("                <div className=\"bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-5\">");
H.push("                  <div className=\"grid grid-cols-2 gap-4\">");
H.push("                    <div className=\"text-center p-4 rounded-xl bg-red-500/10 border border-red-500/20\">");
H.push("                      <div className=\"w-10 h-10 mx-auto mb-2 rounded-full bg-red-500/20 flex items-center justify-center\">");
H.push("                        <Coffee className=\"w-5 h-5 text-red-400\" />");
H.push("                      </div>");
H.push("                      <p className=\"text-xs text-slate-400 line-through\">1 Caf\u00e9 na padaria</p>");
H.push("                      <p className=\"text-lg font-bold text-red-400 line-through\">R$ 6,00</p>");
H.push("                    </div>");
H.push("                    <div className=\"text-center p-4 rounded-xl bg-green-500/10 border border-green-500/20\">");
H.push("                      <div className=\"w-10 h-10 mx-auto mb-2 rounded-full bg-green-500/20 flex items-center justify-center\">");
H.push("                        <Shield className=\"w-5 h-5 text-green-400\" />");
H.push("                      </div>");
H.push("                      <p className=\"text-xs text-slate-300\">10 Dias de Prote\u00e7\u00e3o</p>");
H.push("                      <p className=\"text-lg font-bold text-green-400\">R$ 6,00</p>");
H.push("                    </div>");
H.push("                  </div>");
H.push("                  <p className=\"text-center text-sm text-slate-400 mt-3 font-medium\">Fa\u00e7a a escolha inteligente.</p>");
H.push("                </div>");
H.push("              </motion.div>");
H.push("            </div>");
H.push("          </div>");
H.push("        </section>");

const newHero = H.join("\n");
const s2 = c.indexOf(START);
const e2 = c.indexOf(END);
const before = c.substring(0, s2);
const after = c.substring(e2);
c = before + newHero + "\n\n        " + after;
fs.writeFileSync("app/page.tsx", c, "utf8");
console.log("HERO ATUALIZADO!");
console.log("Recarregue localhost:3000");
