const fs = require("fs");
const comp = [
"\"use client\"","",
"import { useState } from \"react\"","import { Droplets, MapPin, Ruler, Dog, ZoomIn, X, Play, ImageIcon } from \"lucide-react\"","",
"interface GalleryItem {",
"  id: number","  title: string","  desc: string","  icon: string","  color: string",
"  imageUrl: string","  videoId: string  // YouTube ID","  mediaType: \"image\" | \"video\"","}","",
"const items: GalleryItem[] = [",
"  { id:1, title:\"Teste de Resist\u00eancia \u00e0 \u00c1gua\", desc:\"Certifica\u00e7\u00e3o IP67 \u2014 submerso em 1m por 30min sem falhas.\", icon:\"Droplets\", color:\"blue\", imageUrl:\"\", videoId:\"\", mediaType:\"image\" },",
"  { id:2, title:\"Precis\u00e3o do Mapa\", desc:\"GPS 4G multi-operadora com margem de apenas 2 metros.\", icon:\"MapPin\", color:\"green\", imageUrl:\"\", videoId:\"\", mediaType:\"image\" },",
"  { id:3, title:\"Tamanho Compacto\", desc:\"Menor que uma moeda de R$ 1,00. Leve na coleira.\", icon:\"Ruler\", color:\"purple\", imageUrl:\"\", videoId:\"\", mediaType:\"image\" },",
"  { id:4, title:\"Pet Confort\u00e1vel\", desc:\"Design ergon\u00f4mico \u2014 seu pet nem percebe.\", icon:\"Dog\", color:\"amber\", imageUrl:\"\", videoId:\"\", mediaType:\"image\" },",
"]","",
"const iconMap: Record<string, React.ElementType> = { Droplets, MapPin, Ruler, Dog }","",
"const colorMap: Record<string, { bg: string, text: string }> = {",
"  blue: { bg: \"from-blue-500/20 to-blue-600/10 border-blue-500/20\", text: \"text-blue-400\" },",
"  green: { bg: \"from-green-500/20 to-green-600/10 border-green-500/20\", text: \"text-green-400\" },",
"  purple: { bg: \"from-purple-500/20 to-purple-600/10 border-purple-500/20\", text: \"text-purple-400\" },",
"  amber: { bg: \"from-amber-500/20 to-amber-600/10 border-amber-500/20\", text: \"text-amber-400\" },",
"}","",
"export default function EvidenceGallery() {",
"  const [lightbox, setLightbox] = useState<GalleryItem | null>(null)","",
"  return (",
"    <section className=\"py-16 md:py-24 bg-slate-50\">",
"      <div className=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">",
"        <div className=\"text-center mb-12\">",
"          <h2 className=\"text-3xl md:text-4xl font-bold text-slate-900 mb-3\">Veja a Tecnologia FRT em A\u00e7\u00e3o</h2>",
"          <p className=\"text-lg text-slate-500 max-w-2xl mx-auto\">Imagens e v\u00eddeos reais de clientes e testes de campo.</p>",
"        </div>",
"        <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6\">",
"          {items.map(item => {",
"            const Icon = iconMap[item.icon] || Droplets",
"            const c = colorMap[item.color] || colorMap.blue",
"            const hasVideo = !!item.videoId",
"            const hasImage = !!item.imageUrl",
"            return (",
"              <div key={item.id} onClick={() => setLightbox(item)} className=\"group cursor-pointer bg-white rounded-2xl border border-gray-100 overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1\">",
"                <div className={`relative h-48 bg-gradient-to-br ${c.bg} border-b flex items-center justify-center overflow-hidden`}>",
"                  {hasImage ? (",
"                    <img src={item.imageUrl} alt={item.title} className=\"absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500\" />",
"                  ) : hasVideo ? (",
"                    <>",
"                      <img src={`https://img.youtube.com/vi/${item.videoId}/hqdefault.jpg`} alt={item.title} className=\"absolute inset-0 w-full h-full object-cover opacity-80\" />",
"                      <div className=\"absolute inset-0 bg-black/30 flex items-center justify-center\">",
"                        <div className=\"w-14 h-14 rounded-full bg-white/90 shadow-lg flex items-center justify-center group-hover:scale-110 transition-transform\">",
"                          <Play className=\"w-6 h-6 text-slate-800 ml-1\" />",
"                        </div>",
"                      </div>",
"                    </>",
"                  ) : (",
"                    <div className=\"w-20 h-20 rounded-2xl bg-white/80 backdrop-blur-sm shadow-lg flex items-center justify-center group-hover:scale-110 transition-transform duration-300\">",
"                      <Icon className={`w-10 h-10 ${c.text}`} />",
"                    </div>",
"                  )}",
"                  <div className=\"absolute top-3 right-3 flex gap-1.5\">",
"                    {hasVideo && <div className=\"w-7 h-7 rounded-full bg-red-500/90 flex items-center justify-center\"><Play className=\"w-3 h-3 text-white ml-0.5\" /></div>}",
"                    <div className=\"w-7 h-7 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center opacity-0 group-hover:opacity-100 transition\"><ZoomIn className=\"w-3.5 h-3.5 text-white\" /></div>",
"                  </div>",
"                  {!hasImage && !hasVideo && <p className=\"absolute bottom-3 left-3 text-xs font-medium text-white/70 bg-black/20 backdrop-blur-sm px-2 py-1 rounded-lg\">M\u00eddia em breve</p>}",
"                </div>",
"                <div className=\"p-5\">",
"                  <div className=\"flex items-center gap-2 mb-1\">",
"                    <Icon className={`w-4 h-4 ${c.text}`} />",
"                    <h3 className=\"font-bold text-slate-900 text-sm\">{item.title}</h3>",
"                  </div>",
"                  <p className=\"text-sm text-slate-500 leading-relaxed\">{item.desc}</p>",
"                </div>",
"              </div>",
"            )",
"          })}",
"        </div>",
"        <p className=\"text-center text-sm text-slate-400 mt-8\">Fotos e v\u00eddeos de testes realizados pela equipe FRT Automa\u00e7\u00e3o.</p>",
"      </div>","",
"      {/* LIGHTBOX */}",
"      {lightbox && (",
"        <div className=\"fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4\" onClick={() => setLightbox(null)}>",
"          <button className=\"absolute top-6 right-6 text-white/70 hover:text-white z-10\" onClick={() => setLightbox(null)}><X className=\"w-8 h-8\" /></button>",
"          <div className=\"relative w-full max-w-3xl max-h-[85vh] rounded-2xl overflow-hidden bg-slate-900\" onClick={e => e.stopPropagation()}>",
"            {lightbox.videoId ? (",
"              <div className=\"aspect-video\">",
"                <iframe src={`https://www.youtube.com/embed/${lightbox.videoId}?autoplay=1&rel=0`} className=\"w-full h-full\" allow=\"autoplay; encrypted-media\" allowFullScreen />",
"              </div>",
"            ) : lightbox.imageUrl ? (",
"              <img src={lightbox.imageUrl} alt={lightbox.title} className=\"w-full max-h-[70vh] object-contain\" />",
"            ) : (",
"              <div className=\"aspect-video flex items-center justify-center\">",
"                <p className=\"text-slate-400\">M\u00eddia ser\u00e1 adicionada em breve</p>",
"              </div>",
"            )}",
"            <div className=\"p-6\">",
"              <h3 className=\"font-bold text-lg text-white mb-1\">{lightbox.title}</h3>",
"              <p className=\"text-slate-400\">{lightbox.desc}</p>",
"            </div>",
"          </div>",
"        </div>",
"      )}",
"    </section>",
"  )","}",
].join("\n");
fs.writeFileSync("components/EvidenceGallery.tsx", comp, "utf8");
console.log("[OK] EvidenceGallery.tsx atualizado com suporte a video + imagem + lightbox!");
